name: "build sshd"

on:
  push:
    paths:
      - 'sshd/**'
      - '.github/workflows/build_sshd.yaml'
  pull_request:
    paths:
      - 'sshd/**'
      - '.github/workflows/build_sshd.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./sshd
          push: true
          tags: ghcr.io/takutakahashi/images/sshd:${{ github.sha }}