name: "build all"

on:
  push:

jobs:
  build:
    uses: takutakahashi/github-actions/.github/workflows/ghcr.yaml@main
    with:
      path: pvr-base
      image: takutakahashi/pvr-base:${{ github.sha }}
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        run: docker run --privileged -v /lib/firmware:/lib/firmware /lib/modules:/lib/modules ghcr.io/takutakahashi/pvr-base:${{ github.sha }}

