name: "build all"

on:
  push:

jobs:
  build:
    uses: takutakahashi/github-actions/.github/workflows/ghcr.yaml@main
    with:
      path: pvr-base
      image: takutakahashi/pvr-base:latest
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/takutakahashi/pvr-base:latest
    steps:
      -
        run: /px4.sh

